### PR TITLE
Add "rif" subcommand description to interfaces counters

### PR DESCRIPTION
**Pull request by noaOrMlnx**
**- What I did**
Added "rif" subcommand to CLI reference guide
**- How I did it**
Edited command_reference.md file
**- How to verify it**
N/A
**- Previous command output (if the output of a command-line utility has changed)**
N/A
**- New command output (if the output of a command-line utility has changed)**
N/A

### CODE REVIEW

**Comment by liat-grozovik** [comment]
@noaOrMlnx  was this already upstreamed or should i review it?

**Comment by noaOrMlnx** [comment]
@liat-grozovik 
you should review

**Review by liat-grozovik — APPROVED** [review]

**Comment by liat-grozovik** [comment]
@noaOrMlnx once you can please send it CI and then to public PR

**Comment by noaOrMlnx** [comment]
@liat-grozovik  you already merged it to Azure/201911 :) - https://github.com/Azure/sonic-utilities/pull/1373

**Pull request closed without merging**
